export const unitedKingBakersMenuSeed = [
  // ==================== SAVORIES ====================
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Chicken Patty',
    description: 'Crispy flaky pastry filled with spiced chicken',
    category: 'Savories',
    price: 45,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 1,
    sku: 'UKB-SAV-001',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Vegetable Puff',
    description: 'Golden puff pastry with mixed vegetables',
    category: 'Savories',
    price: 35,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 2,
    sku: 'UKB-SAV-002',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Chicken Roll',
    description: 'Soft roll with seasoned chicken filling',
    category: 'Savories',
    price: 50,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 3,
    sku: 'UKB-SAV-003',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Pizza Puff',
    description: 'Puff pastry with pizza toppings and cheese',
    category: 'Savories',
    price: 55,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 4,
    sku: 'UKB-SAV-004',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Sausage Roll',
    description: 'Flaky pastry wrapped around savory sausage',
    category: 'Savories',
    price: 60,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 5,
    sku: 'UKB-SAV-005',
  },

  // ==================== SWEETS ====================
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Gulab Jamun',
    description: 'Traditional milk-solid sweet in sugar syrup',
    category: 'Sweets',
    price: 1000,
    unitType: 'weight',
    baseUnit: 'kg',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 1,
    sku: 'UKB-SWT-001',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Rasgulla',
    description: 'Soft cottage cheese balls in light syrup',
    category: 'Sweets',
    price: 45,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 2,
    sku: 'UKB-SWT-002',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Kheer',
    description: 'Creamy rice pudding with cardamom and nuts',
    category: 'Sweets',
    price: 320,
    unitType: 'volume',
    baseUnit: 'liter',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 3,
    sku: 'UKB-SWT-003',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Barfi',
    description: 'Sweet milk fudge with pistachios',
    category: 'Sweets',
    price: 1200,
    unitType: 'weight',
    baseUnit: 'kg',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 4,
    sku: 'UKB-SWT-004',
  },

  // ==================== BREADS & RUSKS ====================
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'White Bread',
    description: 'Fresh soft white bread loaf',
    category: 'Breads & Rusks',
    price: 120,
    unitType: 'countable',
    baseUnit: 'loaf',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 1,
    sku: 'UKB-BRD-001',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Brown Bread',
    description: 'Whole wheat brown bread loaf',
    category: 'Breads & Rusks',
    price: 140,
    unitType: 'countable',
    baseUnit: 'loaf',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 2,
    sku: 'UKB-BRD-002',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Regular Rusk',
    description: 'Crispy twice-baked bread slices',
    category: 'Breads & Rusks',
    price: 180,
    unitType: 'countable',
    baseUnit: 'pack',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 3,
    sku: 'UKB-RSK-001',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Milk Rusk',
    description: 'Sweet milk-flavored rusks',
    category: 'Breads & Rusks',
    price: 200,
    unitType: 'countable',
    baseUnit: 'pack',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 4,
    sku: 'UKB-RSK-002',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Elaichi Rusk',
    description: 'Cardamom-flavored premium rusks',
    category: 'Breads & Rusks',
    price: 220,
    unitType: 'countable',
    baseUnit: 'pack',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 5,
    sku: 'UKB-RSK-003',
  },

  // ==================== CAKE ====================
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Chocolate Cake',
    description: 'Rich chocolate sponge with chocolate frosting',
    category: 'Cake',
    price: 225,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 1,
    sku: 'UKB-CKE-001',
    variants: [
      { name: 'Half Pound', price: 225, isAvailable: true },
      { name: '1 Pound', price: 450, isAvailable: true },
      { name: '2 Pounds', price: 900, isAvailable: true },
      { name: '3 Pounds', price: 1350, isAvailable: true },
    ],
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Vanilla Cake',
    description: 'Classic vanilla sponge with buttercream',
    category: 'Cake',
    price: 200,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 2,
    sku: 'UKB-CKE-002',
    variants: [
      { name: 'Half Pound', price: 200, isAvailable: true },
      { name: '1 Pound', price: 400, isAvailable: true },
      { name: '2 Pounds', price: 800, isAvailable: true },
      { name: '3 Pounds', price: 1200, isAvailable: true },
    ],
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Black Forest Cake',
    description: 'Chocolate cake with cherries and whipped cream',
    category: 'Cake',
    price: 275,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 3,
    sku: 'UKB-CKE-003',
    variants: [
      { name: 'Half Pound', price: 275, isAvailable: true },
      { name: '1 Pound', price: 550, isAvailable: true },
      { name: '2 Pounds', price: 1100, isAvailable: true },
      { name: '3 Pounds', price: 1650, isAvailable: true },
    ],
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Red Velvet Cake',
    description: 'Velvety red cake with cream cheese frosting',
    category: 'Cake',
    price: 300,
    unitType: 'countable',
    baseUnit: 'piece',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 4,
    sku: 'UKB-CKE-004',
    variants: [
      { name: 'Half Pound', price: 300, isAvailable: true },
      { name: '1 Pound', price: 600, isAvailable: true },
      { name: '2 Pounds', price: 1200, isAvailable: true },
      { name: '3 Pounds', price: 1800, isAvailable: true },
    ],
  },

  // ==================== NIMCO ====================
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Masala Peanuts',
    description: 'Crunchy roasted peanuts with spices',
    category: 'Nimco',
    price: 600,
    unitType: 'weight',
    baseUnit: 'kg',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 1,
    sku: 'UKB-NMC-001',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Mix Nimco',
    description: 'Assorted savory snacks mix',
    category: 'Nimco',
    price: 720,
    unitType: 'weight',
    baseUnit: 'kg',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 2,
    sku: 'UKB-NMC-002',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Daal Moth',
    description: 'Spicy fried lentil mix',
    category: 'Nimco',
    price: 640,
    unitType: 'weight',
    baseUnit: 'kg',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 3,
    sku: 'UKB-NMC-003',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Chatpata Mix',
    description: 'Tangy and spicy snack mix',
    category: 'Nimco',
    price: 680,
    unitType: 'weight',
    baseUnit: 'kg',
    minOrderQty: 0.25,
    orderIncrement: 0.25,
    isAvailable: true,
    sortOrder: 4,
    sku: 'UKB-NMC-004',
  },

  // ==================== DEALS ====================
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Breakfast Deal',
    description: '1 White Bread + 1 Regular Rusk + 6 Chicken Patties',
    category: 'Deals',
    price: 450,
    unitType: 'countable',
    baseUnit: 'combo',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 1,
    sku: 'UKB-DEAL-001',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Tea Time Deal',
    description: '1 Milk Rusk + 6 Vegetable Puffs + 250g Mix Nimco',
    category: 'Deals',
    price: 500,
    unitType: 'countable',
    baseUnit: 'combo',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 2,
    sku: 'UKB-DEAL-002',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Party Pack',
    description: '12 Chicken Patties + 12 Veg Puffs + 1kg Nimco + 2 Rusks',
    category: 'Deals',
    price: 1200,
    unitType: 'countable',
    baseUnit: 'combo',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 3,
    sku: 'UKB-DEAL-003',
  },
  {
    restaurantId: '694fd0fcd114999e836f8666',
    name: 'Sweet Tooth Deal',
    description: '12 Gulab Jamun + 250g Barfi + 250ml Kheer',
    category: 'Deals',
    price: 650,
    unitType: 'countable',
    baseUnit: 'combo',
    minOrderQty: 1,
    orderIncrement: 1,
    isAvailable: true,
    sortOrder: 4,
    sku: 'UKB-DEAL-004',
  },
];
