export const DIALOG_STEPS = {
  // Menu browsing flow
  MENU_SHOW_CATEGORIES: 0,
  MENU_SHOW_ITEMS: 1,
  MENU_SHOW_ITEM_DETAIL: 2,
  MENU_SELECT_QUANTITY: 3,

  // Cart flow
  CART_VIEW: 10,
  CART_EDIT_ITEM: 11,
  CART_CONFIRM_REMOVE: 12,

  // Checkout flow
  CHECKOUT_CONFIRM: 20,
  CHECKOUT_GET_NAME: 21,
  CHECKOUT_GET_ADDRESS: 22,
  CHECKOUT_GET_LOCATION: 23,
  CHECKOUT_CONFIRM_ORDER: 24,
  CHECKOUT_COMPLETE: 25,

  // Order tracking
  TRACKING_SELECT_ORDER: 30,
  TRACKING_VIEW_STATUS: 31,
};
