export const RESTAURANT_DIALOG_STEPS = {
  SELECT_CATEGORY: 0,
  SELECT_ITEM: 1,
  SELECT_VARIANT: 2,
  ASK_QUANTITY: 3,
  ADD_TO_CART: 4,

  VIEW_CART: 10,
  MODIFY_CART: 11,
  ASK_NEW_QUANTITY: 12,
  UPDATE_CART_QUANTITY: 13,

  CHECKOUT_START: 20,
  ASK_DELIVERY_ADDRESS: 21,
  ASK_DELIVERY_INSTRUCTIONS: 22,
  CONFIRM_ORDER: 23,
  ORDER_PLACED: 24,

  ASK_ORDER_ID: 30,
  SHOW_ORDER_DETAILS: 31,
  AWAIT_DELIVERY_CONFIRM: 32,
};
